name: fortawesome

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fortawesome:
    name: fortawesome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: npm install
        run: npm install
      - name: fortawesome
        run: npm run copy:fortawesome